import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const fonts = Instrument_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Noble Aspect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
